name: release

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
      - name: Build binary
        run: |
          GOOS='darwin' GOARCH='arm64' go build -o greeter greeter.go
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: greeter
          path: greeter

      - name: Generate attestation
        uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
        with:
          subject-path: 'greeter'
